# Generated by Django 5.1.5 on 2025-05-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gioco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gioco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite', to='games.gioco')),
            ],
        ),
        migrations.CreateModel(
            name='Proprieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_valore', models.CharField(choices=[('string', 'Stringa'), ('int', 'Intero'), ('float', 'Virgola mobile')], max_length=10)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('giochi', models.ManyToManyField(related_name='proprieta', to='games.gioco')),
            ],
        ),
        migrations.CreateModel(
            name='ValoreProprietaPartita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=255)),
                ('partita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valori_partita', to='games.partita')),
                ('proprieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valori_propieta', to='games.proprieta')),
            ],
        ),
    ]
