# Generated by Django 5.1.5 on 2025-01-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='lenght',
        ),
        migrations.AddField(
            model_name='audio',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
