# Generated by Django 5.1.5 on 2025-01-29 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_management', '0002_remove_audio_lenght_audio_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stutter_percentage', models.FloatField()),
                ('word_matches', models.TextField(blank=True, null=True)),
                ('syllable_matches', models.TextField(blank=True, null=True)),
                ('letter_matches', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='audio_data',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='audio_management.audiodata'),
        ),
    ]
