# Generated by Django 5.1.5 on 2025-01-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_management', '0003_audiodata_audio_audio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='letter_matches',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='audiodata',
            name='syllable_matches',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='audiodata',
            name='word_matches',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
