# Generated by Django 5.1.5 on 2025-01-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='disease_type',
            field=models.CharField(blank=True, choices=[('visiva', 'Visiva'), ('uditiva', 'Uditiva'), ('tattile', 'Tattile')], max_length=20, null=True, verbose_name='tipo di malattia'),
        ),
    ]
